### PR TITLE
feat: add multiselect capability to console.list

### LINKED ISSUE #200: Allow multiselect for `app update`
Allow multiselect for `app update` - makes sense when you want to reset / restart multiple deployments at once.
Should be pretty simple actually since InquirerPy support multiselect in fuzzy search

https://inquirerpy.readthedocs.io/en/latest/pages/prompts/fuzzy.html

What do you think @Schille @buschNT ?

### PR DESCRIPTION
**Pull request by SteinRobert**
Also add to `app update` command.

Closes #200

### CODE REVIEW

**Review by buschNT — APPROVED** [review]
Looks better! Nice. I guess we should merge it now.

**Comment by SteinRobert** [comment]
Alright! Thank you very much for the review. Really appreciate it.

**Comment by Schille** [comment]
Please don't forget the #marketingnotes here. Two, three bullet points what was changed or added.

**Comment by SteinRobert** [comment]
@unikubehq/tech-marketing 
This allows CLI users to run `unikube app update` on multiple apps at once. Previously one had to run `unikube app update` for each app separately. Less typing, more productivity 🎉 Will be included in the next release.

**Pull request merged**
