### PR TITLE
feature/context

### PR DESCRIPTION
**Pull request by buschNT**
Context refactoring.

### CODE REVIEW

**Comment by buschNT** [comment]
@Schille @vvvityaaa I have moved the context into a separate group and refactored the context in all commands. I didn't manage to get some tests for the context running which I commented out. Furthermore we would need to adapt the documentation. After this PR is merged, I am free to work on the tests and check the Documentation.

**Comment by buschNT** [comment]
Closes #113 .

**Comment by Schille** [comment]
Could you please add the new context command group and description to the documentation? There is already a brief section for the context feature here (you may adjust accordingly): https://cli.unikube.io/reference/overview.html#context-management and then add some meaningful docstrings, too.

**Comment by buschNT** [comment]
I adjusted the docs.

**Pull request merged**
